# Generated by Django 2.2.1 on 2020-05-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_spider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
