# Generated by Django 2.2.1 on 2020-03-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brief',
            field=models.CharField(default='欢迎查看本版块帖子', max_length=128, verbose_name='版块简介'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='主题')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Category')),
            ],
        ),
    ]
