# Generated by Django 2.2.1 on 2020-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200311_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_num',
            field=models.IntegerField(default=0, verbose_name='帖子数'),
        ),
    ]
