# Generated by Django 2.2.1 on 2020-03-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbs.Theme'),
        ),
    ]
