# Generated by Django 2.2.1 on 2020-03-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_post_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
