# Generated by Django 2.2.1 on 2020-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20200314_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='imgs/default.png', upload_to='', verbose_name='头像'),
        ),
    ]
