# Generated by Django 2.2.1 on 2020-03-18 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20200314_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='帖子内容'),
        ),
    ]
