# Generated by Django 2.2.1 on 2020-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_auto_20200325_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/head_img/default.png', upload_to='head_img', verbose_name='头像'),
        ),
    ]
