# Generated by Django 2.2.1 on 2020-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_auto_20200328_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='head_img', verbose_name='头像'),
        ),
    ]
