# Generated by Django 2.2.1 on 2020-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20200330_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
