# Generated by Django 2.2.1 on 2020-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
