# Generated by Django 2.2.1 on 2020-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_post_read_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='beidouqixing.png', upload_to='categoryimg'),
        ),
    ]
