# Generated by Django 2.2.1 on 2020-03-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20200319_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
